#############################################################################
# Makefile for building: software-box
# Generated by qmake (2.01a) (Qt 4.8.1) on: ?? ?? 30 23:06:19 2014
# Project:  software-box.pro
# Template: subdirs
# Command: d:\qt\qtsdk\desktop\qt\4.8.1\mingw\bin\qmake.exe -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile software-box.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = d:\qt\qtsdk\desktop\qt\4.8.1\mingw\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-libs \
		sub-pages \
		sub-shared \
		sub-app

libs\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libs\ $(MKDIR) libs\ 
	cd libs\ && $(QMAKE) h:\software-box\libs\libs.pro -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-libs-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libs\ $(MKDIR) libs\ 
	cd libs\ && $(QMAKE) h:\software-box\libs\libs.pro -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-libs: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE)
sub-libs-make_default-ordered: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) 
sub-libs-make_default: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) 
sub-libs-make_first-ordered: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) first
sub-libs-make_first: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) first
sub-libs-all-ordered: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) all
sub-libs-all: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) all
sub-libs-clean-ordered: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) clean
sub-libs-clean: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) clean
sub-libs-distclean-ordered: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) distclean
sub-libs-distclean: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) distclean
sub-libs-install_subtargets-ordered: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) install
sub-libs-install_subtargets: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) install
sub-libs-uninstall_subtargets-ordered: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libs-uninstall_subtargets: libs\$(MAKEFILE) FORCE
	cd libs\ && $(MAKE) -f $(MAKEFILE) uninstall
pages\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) pages\ $(MKDIR) pages\ 
	cd pages\ && $(QMAKE) h:\software-box\pages\pages.pro -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-pages-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) pages\ $(MKDIR) pages\ 
	cd pages\ && $(QMAKE) h:\software-box\pages\pages.pro -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-pages: pages\$(MAKEFILE) FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE)
sub-pages-make_default-ordered: pages\$(MAKEFILE) sub-libs-make_default-ordered  FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) 
sub-pages-make_default: pages\$(MAKEFILE) FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) 
sub-pages-make_first-ordered: pages\$(MAKEFILE) sub-libs-make_first-ordered  FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) first
sub-pages-make_first: pages\$(MAKEFILE) FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) first
sub-pages-all-ordered: pages\$(MAKEFILE) sub-libs-all-ordered  FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) all
sub-pages-all: pages\$(MAKEFILE) FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) all
sub-pages-clean-ordered: pages\$(MAKEFILE) sub-libs-clean-ordered  FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) clean
sub-pages-clean: pages\$(MAKEFILE) FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) clean
sub-pages-distclean-ordered: pages\$(MAKEFILE) sub-libs-distclean-ordered  FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) distclean
sub-pages-distclean: pages\$(MAKEFILE) FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) distclean
sub-pages-install_subtargets-ordered: pages\$(MAKEFILE) sub-libs-install_subtargets-ordered  FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) install
sub-pages-install_subtargets: pages\$(MAKEFILE) FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) install
sub-pages-uninstall_subtargets-ordered: pages\$(MAKEFILE) sub-libs-uninstall_subtargets-ordered  FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-pages-uninstall_subtargets: pages\$(MAKEFILE) FORCE
	cd pages\ && $(MAKE) -f $(MAKEFILE) uninstall
shared\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) shared\ $(MKDIR) shared\ 
	cd shared\ && $(QMAKE) h:\software-box\shared\shared.pro -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-shared-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) shared\ $(MKDIR) shared\ 
	cd shared\ && $(QMAKE) h:\software-box\shared\shared.pro -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-shared: shared\$(MAKEFILE) FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE)
sub-shared-make_default-ordered: shared\$(MAKEFILE) sub-pages-make_default-ordered  FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) 
sub-shared-make_default: shared\$(MAKEFILE) FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) 
sub-shared-make_first-ordered: shared\$(MAKEFILE) sub-pages-make_first-ordered  FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) first
sub-shared-make_first: shared\$(MAKEFILE) FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) first
sub-shared-all-ordered: shared\$(MAKEFILE) sub-pages-all-ordered  FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) all
sub-shared-all: shared\$(MAKEFILE) FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) all
sub-shared-clean-ordered: shared\$(MAKEFILE) sub-pages-clean-ordered  FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) clean
sub-shared-clean: shared\$(MAKEFILE) FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) clean
sub-shared-distclean-ordered: shared\$(MAKEFILE) sub-pages-distclean-ordered  FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) distclean
sub-shared-distclean: shared\$(MAKEFILE) FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) distclean
sub-shared-install_subtargets-ordered: shared\$(MAKEFILE) sub-pages-install_subtargets-ordered  FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) install
sub-shared-install_subtargets: shared\$(MAKEFILE) FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) install
sub-shared-uninstall_subtargets-ordered: shared\$(MAKEFILE) sub-pages-uninstall_subtargets-ordered  FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-shared-uninstall_subtargets: shared\$(MAKEFILE) FORCE
	cd shared\ && $(MAKE) -f $(MAKEFILE) uninstall
app\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) app\ $(MKDIR) app\ 
	cd app\ && $(QMAKE) h:\software-box\app\app.pro -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-app-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) app\ $(MKDIR) app\ 
	cd app\ && $(QMAKE) h:\software-box\app\app.pro -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o $(MAKEFILE)
sub-app: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE)
sub-app-make_default-ordered: app\$(MAKEFILE) sub-shared-make_default-ordered  FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_default: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) 
sub-app-make_first-ordered: app\$(MAKEFILE) sub-shared-make_first-ordered  FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) first
sub-app-make_first: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) first
sub-app-all-ordered: app\$(MAKEFILE) sub-shared-all-ordered  FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) all
sub-app-all: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) all
sub-app-clean-ordered: app\$(MAKEFILE) sub-shared-clean-ordered  FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) clean
sub-app-clean: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) clean
sub-app-distclean-ordered: app\$(MAKEFILE) sub-shared-distclean-ordered  FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-distclean: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) distclean
sub-app-install_subtargets-ordered: app\$(MAKEFILE) sub-shared-install_subtargets-ordered  FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) install
sub-app-install_subtargets: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) install
sub-app-uninstall_subtargets-ordered: app\$(MAKEFILE) sub-shared-uninstall_subtargets-ordered  FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) uninstall
sub-app-uninstall_subtargets: app\$(MAKEFILE) FORCE
	cd app\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: software-box.pro  d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/win32-g++/qmake.conf d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/qconfig.pri \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/modules/qt_webkit_version.pri \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/qt_functions.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/qt_config.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/exclusive_builds.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/default_pre.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/default_pre.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/release.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/debug_and_release.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/default_post.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/default_post.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/rtti.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/exceptions.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/stl.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/shared.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/warn_on.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/qt.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/thread.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/moc.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/win32/windows.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/resources.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/uic.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/yacc.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/lex.prf \
		d:/Qt/qtsdk/Desktop/Qt/4.8.1/mingw/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile software-box.pro
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\qconfig.pri:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\modules\qt_webkit_version.pri:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\qt_functions.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\qt_config.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\exclusive_builds.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\default_pre.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\default_pre.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\release.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\debug_and_release.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\default_post.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\default_post.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\rtti.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\exceptions.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\stl.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\shared.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\warn_on.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\qt.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\thread.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\moc.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\win32\windows.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\resources.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\uic.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\yacc.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\lex.prf:
d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec d:\Qt\qtsdk\Desktop\Qt\4.8.1\mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile software-box.pro

qmake_all: sub-libs-qmake_all sub-pages-qmake_all sub-shared-qmake_all sub-app-qmake_all FORCE

make_default: sub-libs-make_default-ordered sub-pages-make_default-ordered sub-shared-make_default-ordered sub-app-make_default-ordered FORCE
make_first: sub-libs-make_first-ordered sub-pages-make_first-ordered sub-shared-make_first-ordered sub-app-make_first-ordered FORCE
all: sub-libs-all-ordered sub-pages-all-ordered sub-shared-all-ordered sub-app-all-ordered FORCE
clean: sub-libs-clean-ordered sub-pages-clean-ordered sub-shared-clean-ordered sub-app-clean-ordered FORCE
distclean: sub-libs-distclean-ordered sub-pages-distclean-ordered sub-shared-distclean-ordered sub-app-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-libs-install_subtargets-ordered sub-pages-install_subtargets-ordered sub-shared-install_subtargets-ordered sub-app-install_subtargets-ordered FORCE
uninstall_subtargets: sub-libs-uninstall_subtargets-ordered sub-pages-uninstall_subtargets-ordered sub-shared-uninstall_subtargets-ordered sub-app-uninstall_subtargets-ordered FORCE

sub-libs-sub_Debug_ordered: libs\$(MAKEFILE)
	cd libs\ && $(MAKE) -f $(MAKEFILE) debug
sub-pages-sub_Debug_ordered: pages\$(MAKEFILE) sub-libs-sub_Debug_ordered 
	cd pages\ && $(MAKE) -f $(MAKEFILE) debug
sub-shared-sub_Debug_ordered: shared\$(MAKEFILE) sub-pages-sub_Debug_ordered 
	cd shared\ && $(MAKE) -f $(MAKEFILE) debug
sub-app-sub_Debug_ordered: app\$(MAKEFILE) sub-shared-sub_Debug_ordered 
	cd app\ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-libs-sub_Debug_ordered sub-pages-sub_Debug_ordered sub-shared-sub_Debug_ordered sub-app-sub_Debug_ordered

sub-libs-sub_Release_ordered: libs\$(MAKEFILE)
	cd libs\ && $(MAKE) -f $(MAKEFILE) release
sub-pages-sub_Release_ordered: pages\$(MAKEFILE) sub-libs-sub_Release_ordered 
	cd pages\ && $(MAKE) -f $(MAKEFILE) release
sub-shared-sub_Release_ordered: shared\$(MAKEFILE) sub-pages-sub_Release_ordered 
	cd shared\ && $(MAKE) -f $(MAKEFILE) release
sub-app-sub_Release_ordered: app\$(MAKEFILE) sub-shared-sub_Release_ordered 
	cd app\ && $(MAKE) -f $(MAKEFILE) release
release: sub-libs-sub_Release_ordered sub-pages-sub_Release_ordered sub-shared-sub_Release_ordered sub-app-sub_Release_ordered

sub-libs-check_ordered: libs\$(MAKEFILE)
	cd libs\ && $(MAKE) -f $(MAKEFILE) check
sub-pages-check_ordered: pages\$(MAKEFILE) sub-libs-check_ordered 
	cd pages\ && $(MAKE) -f $(MAKEFILE) check
sub-shared-check_ordered: shared\$(MAKEFILE) sub-pages-check_ordered 
	cd shared\ && $(MAKE) -f $(MAKEFILE) check
sub-app-check_ordered: app\$(MAKEFILE) sub-shared-check_ordered 
	cd app\ && $(MAKE) -f $(MAKEFILE) check
check: sub-libs-check_ordered sub-pages-check_ordered sub-shared-check_ordered sub-app-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

